"""add company plan and trial_ends_at

Revision ID: ac213fc06315
Revises: a6b2a2b48764
Create Date: 2026-07-23 17:39:53.033241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac213fc06315'
down_revision: Union[str, Sequence[str], None] = 'a6b2a2b48764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills every pre-existing company (demo companies and
    # any real companies already registered) as 'active', so this migration
    # never retroactively puts an existing customer on a trial countdown.
    # New registrations explicitly pass plan='trial' at insert time, which
    # overrides this default.
    op.add_column('companies', sa.Column('plan', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('companies', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'trial_ends_at')
    op.drop_column('companies', 'plan')
    # ### end Alembic commands ###
